=== simpleinvoices/simpleinvoices/src/reports/PHPReport.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT REPORT (TITLE?,DESC?,PATH?,BACKGROUND_COLOR?,BACKGROUND_IMAGE?,CSS*,SQL?,USER?,PASSWORD?,CONNECTION?,INTERFACE?,DATABASE?,NO_DATA_MSG?,TEMP?,DEBUG?,FORM?,DOCUMENT?,PAGE,GROUPS?)>
<!ATTLIST REPORT MARGINWIDTH CDATA #IMPLIED>
<!ATTLIST REPORT MARGINHEIGHT CDATA #IMPLIED>
<!ATTLIST REPORT MAX_ROW_BUFFER CDATA #IMPLIED>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT DESC (#PCDATA)> 
<!ELEMENT PATH (#PCDATA)> 
<!ELEMENT BACKGROUND_COLOR (#PCDATA)> 
<!ELEMENT BACKGROUND_IMAGE (#PCDATA)> 
<!ELEMENT CSS (#PCDATA)>
<!ATTLIST CSS MEDIA CDATA #IMPLIED>
<!ELEMENT SQL (#PCDATA)> 
<!ELEMENT USER (#PCDATA)> 
<!ELEMENT PASSWORD (#PCDATA)> 
<!ELEMENT CONNECTION (#PCDATA)> 
<!ELEMENT INTERFACE (#PCDATA)> 
<!ELEMENT DATABASE (#PCDATA)> 
<!ELEMENT NO_DATA_MSG (#PCDATA)> 
<!ELEMENT TEMP (#PCDATA)> 
<!ELEMENT DEBUG (#PCDATA)>
<!ELEMENT FORM (FORM_NAME?,FORM_METHOD?,FORM_ACTION?)>
<!ELEMENT FORM_NAME (#PCDATA)>
<!ELEMENT FORM_METHOD (#PCDATA)>
<!ELEMENT FORM_ACTION (#PCDATA)>
<!ELEMENT DOCUMENT (HEADER?,FOOTER?)>
<!ELEMENT HEADER (ROW*)>
<!ELEMENT FOOTER (ROW*)>
<!ELEMENT ROW (COL*)>
<!ELEMENT COL (#PCDATA|LINK|BOOKMARK|XHTML|IMG)*>
<!ATTLIST COL TYPE (REGULAR|EXPRESSION|RAW_EXPRESSION|FIELD) "REGULAR">
<!ATTLIST COL NUMBERFORMAT   CDATA #IMPLIED>
<!ATTLIST COL NUMBERFORMATEX CDATA #IMPLIED>
<!ATTLIST COL CELLCLASS      CDATA #IMPLIED>
<!ATTLIST COL CELLCLASSEVEN  CDATA #IMPLIED>
<!ATTLIST COL CELLCLASSODD   CDATA #IMPLIED>
<!ATTLIST COL CELLCLASSEXPRESSION CDATA #IMPLIED>
<!ATTLIST COL TEXTCLASS		  CDATA #IMPLIED>
<!ATTLIST COL ROWSPAN        CDATA #IMPLIED>
<!ATTLIST COL COLSPAN        CDATA #IMPLIED>
<!ATTLIST COL WIDTH          CDATA #IMPLIED>
<!ATTLIST COL HEIGHT         CDATA #IMPLIED>
<!ATTLIST COL ALIGN          CDATA #IMPLIED>
<!ATTLIST COL VALIGN         CDATA #IMPLIED>
<!ATTLIST COL SUPPRESS (TRUE|FALSE) "FALSE">
<!ELEMENT PAGE (HEADER?,FOOTER?)>
<!ATTLIST PAGE SIZE        CDATA #IMPLIED>
<!ATTLIST PAGE WIDTH       CDATA #IMPLIED>
<!ATTLIST PAGE HEIGHT      CDATA #IMPLIED>
<!ATTLIST PAGE CELLPADDING CDATA #IMPLIED>
<!ATTLIST PAGE CELLSPACING CDATA #IMPLIED>
<!ATTLIST PAGE BORDER      CDATA #IMPLIED>
<!ATTLIST PAGE ALIGN       CDATA #IMPLIED>
<!ELEMENT GROUPS (GROUP+)>
<!ELEMENT GROUP (HEADER?,FIELDS?,FOOTER?,GROUP*)>
<!ATTLIST GROUP NAME CDATA #REQUIRED>
<!ATTLIST GROUP EXPRESSION CDATA #IMPLIED>
<!ATTLIST GROUP PAGEBREAK (TRUE|FALSE) "FALSE">
<!ATTLIST GROUP REPRINT_HEADER_ON_PAGEBREAK (TRUE|FALSE) "FALSE">
<!ATTLIST GROUP RESET_SUPPRESS_ON_PAGEBREAK (TRUE|FALSE) "FALSE">
<!ELEMENT FIELDS (ROW?)>
<!ELEMENT LINK (#PCDATA)>
<!ATTLIST LINK TYPE   (STATIC|DYNAMIC|EXPRESSION) "STATIC">
<!ATTLIST LINK TARGET CDATA #IMPLIED>
<!ATTLIST LINK TITLE  CDATA #IMPLIED>
<!ELEMENT BOOKMARK (#PCDATA)>
<!ATTLIST BOOKMARK TYPE (STATIC|DYNAMIC|EXPRESSION) "STATIC">
<!ATTLIST BOOKMARK CELLCLASS CDATA #IMPLIED>
<!ATTLIST BOOKMARK TEXTCLASS CDATA #IMPLIED>
<!ELEMENT IMG (#PCDATA)>
<!ATTLIST IMG WIDTH CDATA #IMPLIED>
<!ATTLIST IMG HEIGHT CDATA #IMPLIED>
<!ATTLIST IMG BORDER CDATA #IMPLIED>
<!ATTLIST IMG ALT CDATA #IMPLIED>
<!ELEMENT XHTML ANY>

=== simpleinvoices/simpleinvoices/sys/extensions/default_invoice/modules/reports/worktime_total.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE REPORT SYSTEM "PHPReport.dtd">
<REPORT>
	<TITLE>Gewerkte uren per klant</TITLE>
   <BACKGROUND_COLOR>#FFFFFF</BACKGROUND_COLOR>
   <CSS>css/phpreports.css</CSS>  
   <PAGE BORDER="1" SIZE="2500" CELLSPACING="0" CELLPADDING="5" ALIGN="CENTER" WIDTH="500">
      <HEADER>
         <ROW>
            <COL COLSPAN="5" CELLCLASS="PAGE_LAYER" TEXTCLASS="BOLD">Gewerkte uren per klant</COL>
         </ROW>
      </HEADER>		
   </PAGE>
	<GROUPS>
      <GROUP NAME="customer_id" EXPRESSION="customer_id">
	<HEADER>
		<ROW>
			<COL COLSPAN="3"></COL>
		</ROW>
		<ROW>
			<COL COLSPAN="3" TYPE="EXPRESSION" CELLCLASS="HEADER">"Klant: ".$this->getValue("customer_id")</COL>
		</ROW>
	</HEADER>
		<FIELDS>
			<ROW>
				<COL TYPE="FIELD" CELLCLASSEVEN="EVEN" CELLCLASSODD="ODD">tn</COL>
				<COL TYPE="FIELD" CELLCLASSEVEN="EVEN" CELLCLASSODD="ODD">title</COL>
				<COL TYPE="FIELD" CELLCLASSEVEN="EVEN" CELLCLASSODD="ODD">time_unit</COL>
			</ROW>
		</FIELDS>
	<FOOTER>
		<ROW>
			<COL ALIGN="RIGHT" COLSPAN="2" CELLCLASS="FOOTER" TYPE="EXPRESSION">"Totaal ".$this->getRowCount("tn")." tickets  voor ".$this->getValue("customer_id")</COL>
			<COL ALIGN="RIGHT" CELLCLASS="FOOTER" TYPE="EXPRESSION">$this->getSum("time_unit")." min"</COL>
		</ROW>
	</FOOTER>
	</GROUP>
	</GROUPS>
</REPORT>

=== simpleinvoices/simpleinvoices/modules/reports/report_debtors_aging_total.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE REPORT SYSTEM "PHPReport.dtd">
<REPORT>
	<PAGE CELLSPACING="0" CELLPADDING="0" ALIGN="" SIZE="2000">
      <HEADER>
	 	<ROW>
            <COL CELLCLASS="si_rep_head">Total</COL>
            <COL CELLCLASS="si_rep_head">Paid</COL>
            <COL CELLCLASS="si_rep_head">Owing</COL>
            <COL CELLCLASS="si_rep_head">Aging</COL>
         </ROW>
      </HEADER>		
      <FOOTER>
         <ROW>
            <COL CELLCLASS="si_rep_foot" NUMBERFORMATEX="2" TYPE="EXPRESSION">$this->getSum("inv_total")</COL>
            <COL CELLCLASS="si_rep_foot" NUMBERFORMATEX="2" TYPE="EXPRESSION">$this->getSum("inv_paid")</COL>
            <COL CELLCLASS="si_rep_foot" NUMBERFORMATEX="2" TYPE="EXPRESSION">$this->getSum("inv_owing")</COL>
            <COL CELLCLASS="si_rep_foot"></COL>
         </ROW>
      </FOOTER>		
   </PAGE>
	<GROUPS>
      <GROUP NAME="citygroup" >
			<FIELDS>
				<ROW>
					<COL TYPE="FIELD" CELLCLASS="si_rep_td" NUMBERFORMATEX="2">inv_total</COL>
					<COL TYPE="FIELD" CELLCLASS="si_rep_td" NUMBERFORMATEX="2">inv_paid</COL>
					<COL TYPE="FIELD" CELLCLASS="si_rep_td" NUMBERFORMATEX="2">inv_owing</COL>
					<COL TYPE="FIELD" CELLCLASS="si_rep_td" NUMBERFORMATEX="2">aging</COL>
				</ROW>
			</FIELDS>
		</GROUP>
	</GROUPS>
</REPORT>

=== simpleinvoices/simpleinvoices/modules/reports/report_debtors_by_aging.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE REPORT SYSTEM "PHPReport.dtd">
<REPORT NUMBERFORMATEX="2">
	<PAGE CELLSPACING="0" CELLPADDING="0" ALIGN="" SIZE="2000">
      <HEADER>
         <ROW>
				  <COL	CELLCLASS="si_rep_head">id</COL>
				  <COL	CELLCLASS="si_rep_head">Biller</COL>
				  <COL	CELLCLASS="si_rep_head">Customer</COL>
				  <COL	CELLCLASS="si_rep_head">Date</COL>
				  <COL	CELLCLASS="si_rep_head">Age</COL>
				  <COL	CELLCLASS="si_rep_head">Total</COL>
				  <COL	CELLCLASS="si_rep_head">Paid</COL>
				  <COL	CELLCLASS="si_rep_head">Owing</COL>
		</ROW>
      </HEADER>		
      <FOOTER>
         <ROW>
            <COL COLSPAN="7" CELLCLASS="si_rep_foot">Total Owed</COL>
            <COL CELLCLASS="si_rep_foot si_rep_foot_total" NUMBERFORMATEX="2" TYPE="EXPRESSION">$this->getSum("inv_owing")</COL>
         </ROW>
      </FOOTER>		
   </PAGE>
	<GROUPS>
      <GROUP NAME="Aginggroup" EXPRESSION="Aging">
         <HEADER>
            <ROW>
               <COL CELLCLASS="si_rep_group_head">Aging:</COL>
               <COL CELLCLASS="si_rep_group_head" COLSPAN="7" TYPE="EXPRESSION">$this->getValue("Aging")</COL>
            </ROW>
         </HEADER>
         <FOOTER>
            <ROW>
               <COL COLSPAN="7" CELLCLASS="si_rep_group_foot">Sum</COL>
               <COL CELLCLASS="si_rep_group_foot si_rep_group_foot_total" NUMBERFORMATEX="2" TYPE="EXPRESSION">$this->getSum("inv_owing")</COL>
            </ROW>
         </FOOTER>
			<FIELDS>
				<ROW>
					<COL TYPE="FIELD" CELLCLASS="si_rep_td">id</COL>
					<COL TYPE="FIELD" CELLCLASS="si_rep_th">biller</COL>
					<COL TYPE="FIELD" CELLCLASS="si_rep_th">customer</COL>
					<COL TYPE="FIELD" CELLCLASS="si_rep_td">date</COL>
					<COL TYPE="FIELD" CELLCLASS="si_rep_td">age</COL>
					<COL TYPE="FIELD" CELLCLASS="si_rep_td" NUMBERFORMATEX="2">inv_total</COL>
					<COL TYPE="FIELD" CELLCLASS="si_rep_td" NUMBERFORMATEX="2">inv_paid</COL>
					<COL TYPE="FIELD" CELLCLASS="si_rep_td" NUMBERFORMATEX="2">inv_owing</COL>
				</ROW>
			</FIELDS>
		</GROUP>
	</GROUPS>
</REPORT>
